
title: "LocNguyenX"	#must be maximum 9 chars to not break the sidebar
description: "A place to record & share my notes..."
url: "http://locxng.com"
author: locnx


author-image: favicon-62

baseurl: ''  # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown


#color scheme
sidebar-color: '#000'       #those apostrophes are important
accent-color: '#F62459'     #those apostrophes are important


#social
github: https://github.com/locnguyenx
email: mailto:loc.nguyenxuan@gmail.com

#Other
google-custom-search-cx: '008787842287427824110:bd6ovs0skhk'        #Create Custom Search Engine(CSE) with google and find this ID in the code they provide.

destination: ./_site
permalink: /:title/
paginate: 6
paginate_path: /page:num/

sass:
    style: compressed
    
gems: [jekyll-paginate]

author-image: /assets/favicon-62.png
